server:
  port: 8030

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${INITIAL_DB}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    show-sql: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password:
      database: 1
  jwt:
    secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
      root-directory: ${S3_ROOT_DIRECTORY}
      user-directory: ${S3_USER_DIRECTORY}
      profile-directory: ${S3_PROFILE_DIRECTORY}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    cloudfront:
      domain-name: ${CLOUD_FRONT_DISTRIBUTION_DOMAIN}